<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="computerplayer_tests.TestComputerPlayer-20231217160910" tests="10" file="computerplayer_tests.py" time="0.020" timestamp="2023-12-17T16:09:11" failures="1" errors="0" skipped="0">
	<testcase classname="computerplayer_tests.TestComputerPlayer" name="test_check_columns_no_winning_move" time="0.001" timestamp="2023-12-17T16:09:11"/>
	<testcase classname="computerplayer_tests.TestComputerPlayer" name="test_check_columns_winning_move" time="0.001" timestamp="2023-12-17T16:09:11"/>
	<testcase classname="computerplayer_tests.TestComputerPlayer" name="test_check_diagonals_no_winning_move" time="0.001" timestamp="2023-12-17T16:09:11"/>
	<testcase classname="computerplayer_tests.TestComputerPlayer" name="test_check_diagonals_winning_move" time="0.001" timestamp="2023-12-17T16:09:11"/>
	<testcase classname="computerplayer_tests.TestComputerPlayer" name="test_check_rows_no_winning_move" time="0.001" timestamp="2023-12-17T16:09:11"/>
	<testcase classname="computerplayer_tests.TestComputerPlayer" name="test_check_rows_winning_move" time="0.001" timestamp="2023-12-17T16:09:11"/>
	<testcase classname="computerplayer_tests.TestComputerPlayer" name="test_make_fallback_move_center_available" time="0.001" timestamp="2023-12-17T16:09:11"/>
	<testcase classname="computerplayer_tests.TestComputerPlayer" name="test_make_fallback_move_corner_available" time="0.001" timestamp="2023-12-17T16:09:11"/>
	<testcase classname="computerplayer_tests.TestComputerPlayer" name="test_make_move_first_round" time="0.001" timestamp="2023-12-17T16:09:11"/>
	<testcase classname="computerplayer_tests.TestComputerPlayer" name="test_make_fallback_move_side_available" time="0.011" timestamp="2023-12-17T16:09:11">
		<failure type="AssertionError" message="'X' != ' '
- X
+  
"><![CDATA[Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\unittest\case.py", line 57, in testPartExecutor
    yield
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\unittest\case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\unittest\case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "c:\users\pavik\code\ea6 bui_ci\src\unittest\python\computerplayer_tests.py", line 71, in test_make_fallback_move_side_available
    self.assertEqual(self.board.game_grid[1][0], " ")
    ^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\unittest\case.py", line 873, in assertEqual
    assertion_func(first, second, msg=msg)
    ^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\unittest\case.py", line 1253, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
    ^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\unittest\case.py", line 703, in fail
    raise self.failureException(msg)
    ^^^^^^^^^^^^^^^^^
AssertionError: 'X' != ' '
- X
+  

]]></failure>
	</testcase>
</testsuite>
